Repository All-Hands-AI/OpenHands, pull requests merged in 2024-09, with the labels that each got.

#3678 Fix: llm completion exception breaks CodeActAgent
  agenthub/codeact_agent/codeact_agent.py
  openhands/llm/llm.py
Labels: enhancement, agent quality, severity:medium

#3706 Add documentation for CLI mode
  docs/modules/usage/how-to/cli-mode.md
  docs/modules/usage/how-to/headless-mode.md
Labels: documentation, architecture

#3689 (feat) making prompt caching optional instead of enabled default
  agenthub/codeact_agent/codeact_agent.py
  config.template.toml
  docs/modules/usage/llms/llms.md
  openhands/core/config.py
  openhands/core/schema/config.py
  openhands/llm/llm.py
  tests/unit/test_prompt_caching.py
Labels: enhancement, agent quality, severity:medium

#3729 (enh) CodeActAgent: improve logging; sensible retry defaults in config
  agenthub/codeact_agent/codeact_agent.py
  config.template.toml
  docs/i18n/fr/docusaurus-plugin-content-docs/current/usage/llms/llms.md
  docs/i18n/zh-Hans/docusaurus-plugin-content-docs/current/usage/llms/llms.md
  docs/modules/usage/llms/llms.md
  openhands/core/config.py
  openhands/core/message.py
  openhands/llm/llm.py
  openhands/memory/memory.py
Labels: enhancement, agent quality, severity:medium

#3750 (fix) revert enabling litellm verbose mode from testing
  openhands/llm/llm.py
Labels: enhancement

#3780 (enh) add caching@v4 action in workflows
  .github/workflows/ghcr_runtime.yml
  .github/workflows/py-unit-tests.yml
  .github/workflows/regenerate_integration_tests.yml
  openhands/runtime/client/runtime.py
  tests/runtime/test_env_vars.py
Labels: enhancement, backend, test

#3814 Fix wrong mention of Devin in localLLMs.md
  docs/i18n/zh-Hans/docusaurus-plugin-content-docs/current/usage/llms/localLLMs.md
Labels: documentation

#3663 (fix) StuckDetector: syntax error loops were not detected
  openhands/controller/stuck.py
  tests/unit/test_is_stuck.py
Labels: enhancement, agent quality

#3682 (enh) docker pull (if not found locally) with progress info
  openhands/core/main.py
  openhands/runtime/builder/docker.py
  openhands/runtime/utils/runtime_build.py
Labels: enhancement, backend

#3791 (fix) Fix runtime (RT) tests and split tests in 2 actions (openhands/root)
  .github/workflows/ghcr_runtime.yml
  openhands/core/config.py
  openhands/runtime/builder/docker.py
  openhands/runtime/client/client.py
  openhands/runtime/client/runtime.py
  openhands/runtime/plugins/jupyter/__init__.py
  openhands/runtime/remote/runtime.py
  openhands/runtime/runtime.py
  openhands/runtime/utils/__init__.py
  openhands/runtime/utils/runtime_build.py
  openhands/runtime/utils/runtime_templates/Dockerfile.j2
  openhands/runtime/utils/system.py
  pytest.ini
  tests/integration/regenerate.sh
  tests/integration/test_agent.py
  tests/runtime/conftest.py
  tests/runtime/test_bash.py
  tests/runtime/test_browsing.py
  tests/runtime/test_env_vars.py
  tests/runtime/test_images.py
  tests/runtime/test_ipython.py
Labels: enhancement, severity:critical

#3870 (fix) Update logs after run_action (EventStreamRuntime)
  openhands/runtime/client/runtime.py
Labels: enhancement

#3878 (fix) runtime: tweak _wait_until_alive tenacity and exception handling
  openhands/runtime/client/runtime.py
Labels: enhancement

#3869 (feat) Show messages' timestamp in UI
  frontend/src/components/chat/Chat.test.tsx
  frontend/src/components/chat/ChatInterface.test.tsx
  frontend/src/components/chat/ChatInterface.tsx
  frontend/src/components/chat/ChatMessage.test.tsx
  frontend/src/components/chat/ChatMessage.tsx
  frontend/src/components/chat/message.d.ts
  frontend/src/i18n/translation.json
  frontend/src/services/actions.ts
  frontend/src/services/chatService.ts
  frontend/src/state/chatSlice.ts
  frontend/src/types/Message.tsx
  frontend/src/utils/utils.ts
  openhands/events/event.py
  openhands/events/serialization/action.py
  openhands/events/serialization/event.py
  openhands/events/stream.py
  openhands/runtime/client/runtime.py
  tests/integration/mock/eventstream_runtime/ManagerAgent/test_edits/prompt_001.log
  tests/integration/mock/eventstream_runtime/ManagerAgent/test_edits/prompt_002.log
  tests/integration/mock/eventstream_runtime/ManagerAgent/test_edits/prompt_003.log
  tests/integration/mock/eventstream_runtime/ManagerAgent/test_edits/prompt_004.log
  tests/integration/mock/eventstream_runtime/ManagerAgent/test_edits/prompt_005.log
  tests/integration/mock/eventstream_runtime/ManagerAgent/test_edits/prompt_006.log
  tests/integration/mock/eventstream_runtime/ManagerAgent/test_edits/prompt_007.log
  tests/integration/mock/eventstream_runtime/ManagerAgent/test_edits/response_001.log
  tests/integration/mock/eventstream_runtime/ManagerAgent/test_edits/response_003.log
  tests/integration/mock/eventstream_runtime/ManagerAgent/test_edits/response_005.log
  tests/integration/mock/eventstream_runtime/ManagerAgent/test_edits/response_006.log
  tests/integration/mock/eventstream_runtime/ManagerAgent/test_edits/response_007.log
  tests/integration/mock/eventstream_runtime/ManagerAgent/test_simple_task_rejection/prompt_004.log
  tests/integration/mock/eventstream_runtime/ManagerAgent/test_simple_task_rejection/prompt_005.log
  tests/integration/mock/eventstream_runtime/ManagerAgent/test_simple_task_rejection/prompt_006.log
  tests/integration/mock/eventstream_runtime/ManagerAgent/test_simple_task_rejection/prompt_007.log
  tests/integration/mock/eventstream_runtime/ManagerAgent/test_simple_task_rejection/response_001.log
  tests/integration/mock/eventstream_runtime/ManagerAgent/test_simple_task_rejection/response_003.log
  tests/integration/mock/eventstream_runtime/ManagerAgent/test_simple_task_rejection/response_004.log
  tests/integration/mock/eventstream_runtime/ManagerAgent/test_simple_task_rejection/response_005.log
  tests/integration/mock/eventstream_runtime/ManagerAgent/test_simple_task_rejection/response_006.log
  tests/integration/mock/eventstream_runtime/ManagerAgent/test_simple_task_rejection/response_007.log
  tests/integration/mock/eventstream_runtime/ManagerAgent/test_simple_task_rejection/response_008.log
  tests/unit/test_json.py
Labels: enhancement, frontend

#3871 (enh) Dockerfile.j2: improve env vars for bash and activate in .bashrc
  docs/i18n/fr/docusaurus-plugin-content-docs/current/usage/custom_sandbox_guide.md
  docs/modules/usage/architecture/runtime.md
  evaluation/logic_reasoning/run_infer.py
  evaluation/mint/run_infer.py
  evaluation/swe_bench/scripts/eval/convert_oh_output_to_swe_json.py
  evaluation/swe_bench/scripts/eval_infer.sh
  evaluation/swe_bench/scripts/setup/compare_patch_filename.py
  evaluation/swe_bench/scripts/setup/prepare_swe_utils.sh
  evaluation/swe_bench/scripts/setup/swe_entry.sh
  openhands/core/config.py
  openhands/runtime/remote/runtime.py
  openhands/runtime/utils/runtime_build.py
  openhands/runtime/utils/runtime_templates/Dockerfile.j2
Labels: enhancement, backend, severity:medium

#3911 chore: Add docker files for developing inside container.
  Development.md
  Makefile
  compose.yml
  containers/dev/Dockerfile
  containers/dev/README.md
  containers/dev/compose.yml
  containers/dev/dev.sh
Labels: backend

#3925 (feat) LLM class: add safety_settings for Gemini; improve max_output_tokens defaulting
  openhands/llm/llm.py
  tests/unit/test_llm.py
Labels: backend

#3948 ChatMessage: get timestamp out of direct view
  frontend/src/components/chat/ChatMessage.tsx
Labels: frontend

#3970 (fix) CodeActAgent: use `content` of AgentDelegateObservation
  agenthub/codeact_agent/codeact_agent.py
  tests/integration/mock/eventstream_runtime/CodeActAgent/test_browse_internet/prompt_001.log
  tests/integration/mock/eventstream_runtime/CodeActAgent/test_browse_internet/prompt_005.log
Labels: agent quality

#3968 (fix) CodeActAgent/LLM: react on should_exit flag (user cancellation)
  agenthub/codeact_agent/codeact_agent.py
  openhands/core/exceptions.py
  openhands/llm/llm.py
  tests/unit/test_llm.py
Labels: agent quality

#3987 Refactor `config.py` file into package (own folder with separate files)
  openhands/core/config.py
  openhands/core/config/README.md
  openhands/core/config/__init__.py
  openhands/core/config/agent_config.py
  openhands/core/config/app_config.py
  openhands/core/config/config_utils.py
  openhands/core/config/llm_config.py
  openhands/core/config/sandbox_config.py
  openhands/core/config/security_config.py
  openhands/core/config/utils.py
  tests/unit/test_arg_parser.py
Labels: enhancement, architecture

#4095 revert #3871 dockerfile template: don't write to .bashrc file
  .github/workflows/ghcr-build.yml
  openhands/runtime/utils/runtime_templates/Dockerfile.j2
Labels: enhancement, severity:critical

#4098 (enh) add test_python_version to test_bash.py runtime tests
  tests/runtime/test_bash.py
Labels: test

#4108 (fix) Fix logging in shared eval file to prevent key disclosure
  evaluation/utils/shared.py
Labels: evaluation, security
