Repository All-Hands-AI/OpenHands, pull requests merged in 2024-11, with the labels that each got.

#4671 Add Google Sheets integration for GitHub user verification
  openhands/server/github.py
  openhands/server/sheets_client.py
  poetry.lock
  pyproject.toml
Labels: fix-me

#4832 Fix issue #4830: [Bug]: Copy-paste into the "What do you want to build?" bar doesn't work
  frontend/__tests__/components/chat/chat-input.test.tsx
  frontend/src/components/chat-input.tsx
Labels: fix-me

#4977 Context Window Exceeded fix
  openhands/controller/agent_controller.py
  openhands/controller/state/state.py
  tests/unit/test_truncation.py
Labels: eval-this

#5161 docs: Add note about organizational token policies
  openhands/resolver/README.md
Labels: fix-me

#5192 Show the link to the All Hands product roadmap
  README.md
Labels: fix-me

#5108 Add eval workflow that triggers remote eval job
  .github/workflows/run-eval.yml
Labels: run-eval-xs

#5075 [resolver] Select a non-main branch option
  .github/workflows/openhands-resolver.yml
  openhands/resolver/resolve_issue.py
Labels: lint-fix

#5181 Fix issue #5179: [frontend]: Push to Github button should only push branch, but not creating a PR
  frontend/__tests__/components/chat/chat-interface.test.tsx
  frontend/public/config.json
  frontend/src/components/chat-interface.tsx
  frontend/src/components/suggestion-item.tsx
  openhands/agenthub/codeact_agent/codeact_agent.py
  openhands/events/action/message.py
  openhands/events/serialization/action.py
  openhands/resolver/patching/__init__.py
  openhands/resolver/patching/apply.py
  openhands/resolver/patching/exceptions.py
  openhands/resolver/patching/patch.py
  openhands/resolver/patching/snippets.py
  openhands/resolver/prompts/repo_instructions/all-hands-ai___openhands-resolver.txt
  openhands/resolver/prompts/repo_instructions/rbren___rss-parser.txt
  openhands/resolver/prompts/resolve/basic-with-tests.jinja
  openhands/resolver/prompts/resolve/basic.jinja
  openhands/runtime/utils/command.py
  tests/unit/resolver/test_guess_success.py
  tests/unit/resolver/test_issue_handler_error_handling.py
  tests/unit/resolver/test_issue_references.py
  tests/unit/resolver/test_pr_handler_guess_success.py
  tests/unit/resolver/test_pr_title_escaping.py
  tests/unit/resolver/test_resolve_issues.py
Labels: fix-me

#4822 Fix issue #4820: [Bug]: litellm doesn't support function calling model from OpenRouter. bug cause codeactagent couldn't interact with internet solely without ask browser agent for help
  openhands/llm/llm.py
Labels: fix-me

#5077 Fix issue #5076: Integration test github action
  .github/workflows/eval-runner.yml
  .github/workflows/integration-runner.yml
  evaluation/integration_tests/run_infer.py
  evaluation/integration_tests/tests/t05_simple_browsing.py
  evaluation/integration_tests/tests/t06_github_pr_browsing.py
Labels: integration-test
