Repository All-Hands-AI/OpenHands, pull requests merged in 2024-12, with the labels that each got.

#5338 Fix issue #5337: [Bug]: lint-fix workflow is failing frontend and python steps
  .github/workflows/lint-fix.yml
Labels: lint-fix

#5178 docs: add hyperlinks to directories and improve navigation
  CONTRIBUTING.md
Labels: fix-me

#5312 Clicking row should select file
  frontend/src/components/file-explorer/tree-node.tsx
Labels: lint-fix

#5242 Switch dependency to browsergym-core
  .github/workflows/ghcr-build.yml
  poetry.lock
  pyproject.toml
  tests/runtime/test_browsergym_envs.py
  tests/runtime/test_browsing.py
Labels: fix-me, lint-fix

#5393 fix download zip
  frontend/src/api/open-hands.ts
Labels: lint-fix

#5397 Upgrade `openhands-aci` to v0.1.2
  openhands/runtime/action_execution_server.py
  poetry.lock
  pyproject.toml
  tests/unit/test_agent_skill.py
Labels: run-eval-m

#5396 Fix issue #5383: [Bug]: LLM Cost is added to the `metrics` twice
  openhands/llm/llm.py
Labels: fix-me

#5226 Fix issue #5186: [Bug]: Fix up inline code styles in chat window
  frontend/__tests__/components/chat-message.test.tsx
  frontend/src/components/features/markdown/code.tsx
  frontend/src/index.css
  frontend/src/services/actions.ts
Labels: fix-me

#5483 Fix issue #5478: Add color to the line next to "Ran a XXX Command" based on return value
  frontend/__tests__/components/chat/expandable-message.test.tsx
  frontend/src/components/features/chat/expandable-message.tsx
  frontend/src/components/features/chat/messages.tsx
  frontend/src/icons/check-circle-solid.svg
  frontend/src/icons/x-circle-solid.svg
  frontend/src/message.d.ts
  frontend/src/state/chat-slice.ts
  frontend/src/types/core/observations.ts
  frontend/tailwind.config.js
  frontend/test-utils.tsx
  frontend/vitest.setup.ts
  openhands/agenthub/codeact_agent/README.md
  openhands/events/observation/commands.py
  openhands/events/serialization/event.py
  openhands/events/serialization/observation.py
  pyproject.toml
  tests/unit/test_command_success.py
  tests/unit/test_event_serialization.py
  tests/unit/test_observation_serialization.py
  tests/unit/test_security.py
Labels: lint-fix

#5528 Fix issue #5527: Document repository customization and micro-agents
  docs/modules/usage/micro-agents.md
  docs/modules/usage/prompting-best-practices.md
  docs/sidebars.ts
Labels: fix-me-experimental

#5553 fix: serialize tool calls
  openhands/agenthub/codeact_agent/codeact_agent.py
  openhands/core/message.py
  openhands/core/message_format.md
  tests/unit/test_message_serialization.py
Labels: lint-fix, integration-test

#5597 fix: allow to continue when the agent is stuck in interactive mode
  openhands/controller/agent_controller.py
  openhands/controller/state/state.py
  openhands/controller/stuck.py
  tests/unit/test_is_stuck.py
Labels: lint-fix, integration-test

#5600 Remove unused codeact-SWE agent
  evaluation/benchmarks/swe_bench/prompt.py
  evaluation/benchmarks/swe_bench/run_infer.py
  openhands/agenthub/__init__.py
  openhands/agenthub/codeact_swe_agent/README.md
  openhands/agenthub/codeact_swe_agent/__init__.py
  openhands/agenthub/codeact_swe_agent/action_parser.py
  openhands/agenthub/codeact_swe_agent/codeact_swe_agent.py
  openhands/agenthub/codeact_swe_agent/prompt.py
  openhands/agenthub/codeact_swe_agent/response_parser.py
Labels: fix-me

#5550 Small fix and addition for token counting
  config.template.toml
  openhands/core/config/llm_config.py
  openhands/llm/llm.py
  openhands/server/session/session.py
  openhands/server/session/session_init_data.py
  tests/unit/test_config.py
  tests/unit/test_llm.py
Labels: fix-me-experimental, lint-fix

#5408 feat: support directly stream logs from container to stdout in debug mode
  openhands/runtime/impl/eventstream/eventstream_runtime.py
  openhands/runtime/impl/modal/modal_runtime.py
  openhands/runtime/impl/runloop/runloop_runtime.py
  openhands/runtime/utils/log_streamer.py
Labels: fix-me-experimental

#5611 Fix issue #5609: Use litellm's modify_params with default True
  config.template.toml
  evaluation/benchmarks/EDA/run_infer.py
  evaluation/benchmarks/agent_bench/run_infer.py
  evaluation/benchmarks/aider_bench/run_infer.py
  evaluation/benchmarks/biocoder/run_infer.py
  evaluation/benchmarks/bird/run_infer.py
  evaluation/benchmarks/browsing_delegation/run_infer.py
  evaluation/benchmarks/commit0_bench/run_infer.py
  evaluation/benchmarks/discoverybench/run_infer.py
  evaluation/benchmarks/gaia/run_infer.py
  evaluation/benchmarks/gorilla/run_infer.py
  evaluation/benchmarks/gpqa/run_infer.py
  evaluation/benchmarks/humanevalfix/run_infer.py
  evaluation/benchmarks/logic_reasoning/run_infer.py
  evaluation/benchmarks/miniwob/run_infer.py
  evaluation/benchmarks/mint/run_infer.py
  evaluation/benchmarks/ml_bench/run_infer.py
  evaluation/benchmarks/scienceagentbench/run_infer.py
  evaluation/benchmarks/swe_bench/run_infer.py
  evaluation/benchmarks/toolqa/run_infer.py
  evaluation/benchmarks/webarena/run_infer.py
  openhands/core/config/llm_config.py
  openhands/core/config/utils.py
  openhands/llm/llm.py
  pyproject.toml
Labels: fix-me-experimental

#5635 Fix issue #5633: [Bug]: Decimal points in maximum iteration messages not needed
  openhands/controller/agent_controller.py
  tests/unit/test_traffic_control.py
Labels: lint-fix

#5008 Implement file-by-file download with progress
  frontend/src/components/features/chat/action-suggestions.tsx
  frontend/src/components/features/project-menu/ProjectMenuCard.tsx
  frontend/src/components/features/project-menu/project.menu-card-context-menu.tsx
  frontend/src/components/shared/download-modal.tsx
  frontend/src/components/shared/download-progress.tsx
  frontend/src/components/shared/modals/modal-backdrop.tsx
  frontend/src/hooks/use-download-progress.ts
  frontend/src/i18n/translation.json
  frontend/src/types/file-system.d.ts
  frontend/src/utils/download-files.ts
  frontend/tailwind.config.js
  openhands/server/session/manager.py
Labels: lint-fix

#5677 Fix issue #5676: [Bug]: Frontend Hyperlink in Chat window should open link in a new tab
  frontend/src/components/features/chat/chat-message.tsx
  frontend/src/components/features/markdown/anchor.tsx
  openhands/server/session/manager.py
  pyproject.toml
Labels: fix-me-experimental

#5700 feat(eval): add standard error to swebench summarize outputs
  evaluation/benchmarks/swe_bench/scripts/eval/summarize_outputs.py
Labels: fix-me-experimental

#5706 feat: add support for custom PR titles
  openhands/resolver/send_pull_request.py
  tests/unit/resolver/test_send_pull_request.py
Labels: lint-fix

#5753 Fix issue #5752: Install "jq" by default in OpenHands runtime
  openhands/runtime/utils/runtime_templates/Dockerfile.j2
Labels: fix-me

#5740 Fix issue #5739: [Bug]: Move ./evaluation/swe_bench/scripts/cleanup_remote_runtime.sh to general eval utils
  evaluation/benchmarks/commit0_bench/README.md
  evaluation/benchmarks/swe_bench/README.md
  evaluation/benchmarks/swe_bench/scripts/cleanup_remote_runtime.sh
  evaluation/utils/scripts/cleanup_remote_runtime.sh
Labels: fix-me-experimental

#5891 Fix issue #5890: Add an automatic check of version consistency in documentation
  .github/scripts/check_version_consistency.py
  .github/workflows/lint.yml
  docs/i18n/fr/docusaurus-plugin-content-docs/current/usage/how-to/cli-mode.md
  docs/i18n/fr/docusaurus-plugin-content-docs/current/usage/how-to/headless-mode.md
  docs/i18n/fr/docusaurus-plugin-content-docs/current/usage/installation.mdx
  docs/i18n/fr/docusaurus-plugin-content-docs/current/usage/runtimes.md
  docs/i18n/zh-Hans/docusaurus-plugin-content-docs/current/usage/how-to/cli-mode.md
  docs/i18n/zh-Hans/docusaurus-plugin-content-docs/current/usage/how-to/headless-mode.md
  docs/i18n/zh-Hans/docusaurus-plugin-content-docs/current/usage/installation.mdx
  docs/i18n/zh-Hans/docusaurus-plugin-content-docs/current/usage/runtimes.md
Labels: fix-me

#5833 Fix issue #5831: [Bug]: "Request failed with status code 409" on opening empty repo
  frontend/__tests__/api/github.test.ts
  frontend/src/api/github.ts
  frontend/src/services/settings.ts
Labels: fix-me

#5666 Reset a failed tool call
  openhands/agenthub/codeact_agent/codeact_agent.py
  openhands/controller/agent_controller.py
  openhands/llm/llm.py
  tests/unit/test_agent_controller.py
Labels: lint-fix
