Repository All-Hands-AI/OpenHands, pull requests merged in 2025-05, with the labels that each got.

#7514 [Feat]: Add timestamp info to CmdOutputObservation
  openhands/events/observation/commands.py
Labels: run-eval-m

#8501 Revert "Make str_replace_editor description more clear (#8434)"
  openhands/agenthub/codeact_agent/tools/str_replace_editor.py
  poetry.lock
Labels: run-eval-50

#8106 Add timeout parameter to bash tool for hard timeout control
  openhands/agenthub/codeact_agent/function_calling.py
  openhands/agenthub/codeact_agent/tools/bash.py
  tests/unit/test_function_calling.py
Labels: run-eval-50

#8310 Fix issue #8304: [Bug]: Non-native tool use converter fails when builtin tools are disabled
  openhands/agenthub/codeact_agent/README.md
  openhands/agenthub/codeact_agent/tools/bash.py
  openhands/agenthub/codeact_agent/tools/browser.py
  openhands/agenthub/codeact_agent/tools/finish.py
  openhands/agenthub/codeact_agent/tools/str_replace_editor.py
  openhands/llm/fn_call_converter.py
  openhands/llm/tool_names.py
  tests/unit/test_llm_fncall_converter.py
Labels: lint-fix

#7440 build(makefile) Develop in OpenhandsCloud
  Makefile
Labels: Stale

#8264 Add CLIRuntime implementation for local command execution
  .github/workflows/py-unit-tests.yml
  openhands/agenthub/codeact_agent/codeact_agent.py
  openhands/agenthub/codeact_agent/function_calling.py
  openhands/agenthub/readonly_agent/function_calling.py
  openhands/cli/main.py
  openhands/cli/settings.py
  openhands/cli/tui.py
  openhands/controller/agent_controller.py
  openhands/core/config/agent_config.py
  openhands/core/config/app_config.py
  openhands/core/config/utils.py
  openhands/events/observation/agent.py
  openhands/events/stream.py
  openhands/integrations/gitlab/gitlab_service.py
  openhands/mcp/utils.py
  openhands/resolver/interfaces/issue_definitions.py
  openhands/runtime/__init__.py
  openhands/runtime/base.py
  openhands/runtime/impl/__init__.py
  openhands/runtime/impl/action_execution/action_execution_client.py
  openhands/runtime/impl/cli/__init__.py
  openhands/runtime/impl/cli/cli_runtime.py
  openhands/runtime/impl/local/local_runtime.py
  tests/runtime/conftest.py
  tests/runtime/test_aci_edit.py
  tests/runtime/test_bash.py
  tests/runtime/test_browsing.py
  tests/runtime/test_docker_images.py
  tests/runtime/test_env_vars.py
  tests/runtime/test_glob_and_grep.py
  tests/runtime/test_ipython.py
  tests/runtime/test_mcp_action.py
  tests/runtime/test_microagent.py
  tests/runtime/test_replay.py
  tests/unit/core/config/test_config_utils.py
  tests/unit/test_arg_parser.py
  tests/unit/test_cli.py
  tests/unit/test_cli_workspace.py
  tests/unit/test_runtime_git_tokens.py
Labels: fix-me-experimental, lint-fix
