Repository All-Hands-AI/OpenHands, pull requests merged in 2025-08, with the labels that each got.

#9942 [Feature Request]: Make git username and email configurable
  openhands/agenthub/codeact_agent/prompts/system_prompt.j2
  openhands/agenthub/codeact_agent/prompts/system_prompt_interactive.j2
  openhands/agenthub/codeact_agent/prompts/system_prompt_long_horizon.j2
  openhands/core/config/openhands_config.py
  openhands/resolver/send_pull_request.py
  openhands/runtime/action_execution_server.py
  openhands/runtime/utils/command.py
  tests/unit/resolver/github/test_send_pull_request.py
  tests/unit/resolver/gitlab/test_gitlab_send_pull_request.py
  tests/unit/test_git_config.py
Labels: needs-review

#9826 Paginate repo list from providers
  frontend/__tests__/components/features/home/repo-connector.test.tsx
  frontend/__tests__/components/features/home/repo-selection-form.test.tsx
  frontend/__tests__/components/features/home/task-card.test.tsx
  frontend/__tests__/components/features/microagent-management/microagent-management.test.tsx
  frontend/__tests__/routes/git-settings.test.tsx
  frontend/__tests__/routes/home-screen.test.tsx
  frontend/package-lock.json
  frontend/package.json
  frontend/public/mockServiceWorker.js
  frontend/src/api/open-hands.ts
  frontend/src/components/common/git-branch-dropdown.tsx
  frontend/src/components/common/git-provider-dropdown.tsx
  frontend/src/components/common/git-repository-dropdown.tsx
  frontend/src/components/common/react-select-async-dropdown.tsx
  frontend/src/components/common/react-select-dropdown.tsx
  frontend/src/components/common/react-select-styles.ts
  frontend/src/components/features/home/repo-selection-form.tsx
  frontend/src/components/features/home/repository-selection/index.ts
  frontend/src/components/features/home/repository-selection/repository-dropdown.tsx
  frontend/src/components/features/home/repository-selection/repository-error-state.tsx
  frontend/src/components/features/home/repository-selection/repository-loading-state.tsx
  frontend/src/components/features/microagent-management/microagent-management-sidebar.tsx
  frontend/src/components/features/settings/settings-dropdown-input.tsx
  frontend/src/entry.client.tsx
  frontend/src/hooks/query/use-app-installations.ts
  frontend/src/hooks/query/use-git-repositories.ts
  frontend/src/hooks/query/use-installation-repositories.ts
  frontend/src/hooks/query/use-search-repositories.ts
  frontend/src/hooks/query/use-user-repositories.ts
  frontend/src/mocks/git-repository-handlers.ts
  frontend/src/mocks/handlers.ts
  frontend/src/utils/utils.ts
  openhands/integrations/bitbucket/bitbucket_service.py
  openhands/integrations/github/github_service.py
  openhands/integrations/gitlab/gitlab_service.py
  openhands/integrations/provider.py
  openhands/integrations/service_types.py
  openhands/server/routes/git.py
  tests/unit/test_bitbucket.py
  tests/unit/test_github_service.py
  tests/unit/test_gitlab.py
Labels: needs-qa

#10118 Fix authentication setup issues in unit tests
  tests/unit/test_get_repository_microagents.py
  tests/unit/test_middleware.py
Labels: needs-review

#9783 feat(cli): Use CLI to launch OpenHands UI server via Docker
  .github/scripts/update_pr_description.sh
  docs/usage/how-to/gui-mode.mdx
  docs/usage/local-setup.mdx
  evaluation/benchmarks/EDA/run_infer.py
  evaluation/benchmarks/commit0/run_infer.py
  evaluation/benchmarks/gaia/run_infer.py
  evaluation/benchmarks/gorilla/run_infer.py
  evaluation/benchmarks/gpqa/run_infer.py
  evaluation/benchmarks/lca_ci_build_repair/eval_infer.py
  evaluation/benchmarks/lca_ci_build_repair/run_infer.py
  evaluation/benchmarks/logic_reasoning/run_infer.py
  evaluation/benchmarks/mint/run_infer.py
  evaluation/benchmarks/ml_bench/run_analysis.py
  evaluation/benchmarks/ml_bench/run_infer.py
  evaluation/benchmarks/multi_swe_bench/eval_infer.py
  evaluation/benchmarks/multi_swe_bench/run_infer.py
  evaluation/benchmarks/scienceagentbench/run_infer.py
  evaluation/benchmarks/swe_bench/eval_infer.py
  evaluation/benchmarks/swe_bench/run_infer.py
  evaluation/benchmarks/swe_bench/run_infer_interact.py
  evaluation/benchmarks/swe_bench/run_localize.py
  evaluation/benchmarks/testgeneval/eval_infer.py
  evaluation/benchmarks/testgeneval/run_infer.py
  evaluation/benchmarks/the_agent_company/run_infer.py
  evaluation/benchmarks/toolqa/run_infer.py
  evaluation/benchmarks/visual_swe_bench/run_infer.py
  openhands/cli/__init__.py
  openhands/cli/entry.py
  openhands/cli/gui_launcher.py
  openhands/cli/main.py
  openhands/core/config/__init__.py
  openhands/core/config/arg_utils.py
  openhands/core/config/utils.py
  openhands/utils/term_color.py
  pyproject.toml
  tests/unit/test_arg_parser.py
  tests/unit/test_cli.py
Labels: enhancement, CLI, needs-qa

#10116 Add Playwright-based end-to-end testing workflow
  .github/workflows/e2e-tests.yml
  .github/workflows/py-tests.yml
  .gitignore
  frontend/package-lock.json
  frontend/vite.config.ts
  poetry.lock
  pyproject.toml
  tests/e2e/README.md
  tests/e2e/check_playwright.py
  tests/e2e/conftest.py
  tests/e2e/pytest.ini
  tests/e2e/test_e2e_workflow.py
Labels: enhancement, end-to-end

#10389 runtime(bash): clarify guidance when previous command still running; recommend execute_bash timeout (issue #10350)
  openhands/runtime/utils/bash.py
  openhands/runtime/utils/bash_constants.py
  openhands/runtime/utils/windows_bash.py
Labels: enhancement, agent

#10306 feat(agent): include a new roleplay-based prompt
  openhands/agenthub/codeact_agent/prompts/system_prompt_tech_philosophy.j2
Labels: run-eval-100

#10406 fix(frontend): browser tab notification respects user-renamed titles
  frontend/__tests__/utils/browser-tab.test.ts
  frontend/src/utils/browser-tab.ts
Labels: frontend, bugfix

#10420 Allow user actions over websockets
  openhands/memory/conversation_memory.py
Labels: lint-fix

#10512 feat(config-writer): tomlkit-based writer with comment preservation, explicit APIs, atomic writes + add tomlkit dep
  openhands/core/config/openhands_config.py
  openhands/core/config/toml_writer.py
  openhands/llm/__init__.py
  poetry.lock
  pyproject.toml
  tests/unit/config/test_toml_writer.py
  tests/unit/config/test_toml_writer_agent.py
  tests/unit/config/test_toml_writer_condenser.py
  tests/unit/config/test_toml_writer_preservation.py
  tests/unit/config/test_toml_writer_remove.py
  tests/unit/config/test_toml_writer_roundtrip.py
Labels: lint-fix

#10537 Fix: expose aggregated LLM metrics in State for evaluation scripts
  evaluation/benchmarks/EDA/run_infer.py
  evaluation/benchmarks/agent_bench/run_infer.py
  evaluation/benchmarks/aider_bench/run_infer.py
  evaluation/benchmarks/biocoder/run_infer.py
  evaluation/benchmarks/bird/run_infer.py
  evaluation/benchmarks/browsing_delegation/run_infer.py
  evaluation/benchmarks/commit0/run_infer.py
  evaluation/benchmarks/discoverybench/run_infer.py
  evaluation/benchmarks/gaia/run_infer.py
  evaluation/benchmarks/gorilla/run_infer.py
  evaluation/benchmarks/gpqa/run_infer.py
  evaluation/benchmarks/humanevalfix/run_infer.py
  evaluation/benchmarks/lca_ci_build_repair/run_infer.py
  evaluation/benchmarks/logic_reasoning/run_infer.py
  evaluation/benchmarks/miniwob/run_infer.py
  evaluation/benchmarks/mint/run_infer.py
  evaluation/benchmarks/ml_bench/run_infer.py
  evaluation/benchmarks/scienceagentbench/run_infer.py
  evaluation/benchmarks/swe_bench/run_infer_interact.py
  evaluation/benchmarks/toolqa/run_infer.py
  evaluation/benchmarks/visualwebarena/run_infer.py
  evaluation/benchmarks/webarena/run_infer.py
  evaluation/integration_tests/run_infer.py
  evaluation/utils/shared.py
  tests/unit/test_state_metrics_exposure.py
Labels: bug, run-eval-2

#10477 feat(agent): add security-related items in system prompt to defense against data exfiltration
  openhands/agenthub/codeact_agent/prompts/system_prompt.j2
Labels: run-eval-50

#9692 Fixes bug 9682
  openhands/cli/main.py
  openhands/cli/suppress_warnings.py
  openhands/server/__main__.py
Labels: needs-qa

#10255 feat: Add OPENHANDS_FORCE_VISION env var to override vision capability detection
  openhands/llm/llm.py
Labels: lint-fix
