Repository All-Hands-AI/OpenHands, pull requests merged in 2025-07, with the labels that each got.

#9402 Add labels support to PR and MR creation tools
  openhands/integrations/github/github_service.py
  openhands/integrations/gitlab/gitlab_service.py
  openhands/server/routes/mcp.py
Labels: needs-qa

#9406 Fix capitalization in 'Initializing agent...' status message
  frontend/src/i18n/translation.json
Labels: needs-qa

#9471 Enhance logging for org-level microagent loading to improve debugging
  openhands/runtime/base.py
Labels: needs-qa

#8592 feat(frontend): Memory UI
  frontend/__tests__/components/chat-message.test.tsx
  frontend/__tests__/components/features/chat/launch-microagent-modal.test.tsx
  frontend/__tests__/components/features/chat/messages.test.tsx
  frontend/__tests__/components/features/home/home-header.test.tsx
  frontend/__tests__/components/features/home/repo-connector.test.tsx
  frontend/__tests__/components/features/home/repo-selection-form.test.tsx
  frontend/__tests__/components/features/home/task-card.test.tsx
  frontend/__tests__/components/shared/inputs/badge-input.test.tsx
  frontend/__tests__/microagent-status-indicator.test.tsx
  frontend/__tests__/parse-pr-url.test.ts
  frontend/__tests__/utils/check-home-hardcoded-strings.test.tsx
  frontend/scripts/check-unlocalized-strings.cjs
  frontend/src/api/memory-service/memory-service.api.ts
  frontend/src/api/open-hands.ts
  frontend/src/api/open-hands.types.ts
  frontend/src/components/features/chat/chat-message.tsx
  frontend/src/components/features/chat/event-message.tsx
  frontend/src/components/features/chat/messages.tsx
  frontend/src/components/features/chat/microagent/launch-microagent-modal.tsx
  frontend/src/components/features/chat/microagent/loading-microagent-body.tsx
  frontend/src/components/features/chat/microagent/loading-microagent-textarea.tsx
  frontend/src/components/features/chat/microagent/microagent-status-indicator.tsx
  frontend/src/components/features/chat/microagent/microagent-status-toast.tsx
  frontend/src/components/features/conversation-panel/conversation-card.tsx
  frontend/src/components/features/conversation-panel/microagents-modal.tsx
  frontend/src/components/features/home/home-header.tsx
  frontend/src/components/features/home/repo-selection-form.test.tsx
  frontend/src/components/features/home/repo-selection-form.tsx
  frontend/src/components/features/home/tasks/task-card.tsx
  frontend/src/components/features/settings/settings-dropdown-input.tsx
  frontend/src/components/shared/badge.tsx
  frontend/src/components/shared/buttons/copy-to-clipboard-button.tsx
  frontend/src/components/shared/inputs/badge-input.tsx
  frontend/src/context/conversation-subscriptions-provider.tsx
  frontend/src/context/ws-client-provider.tsx
  frontend/src/entry.client.tsx
  frontend/src/hooks/mutation/use-create-conversation.ts
  frontend/src/hooks/query/use-conversation-microagents.ts
  frontend/src/hooks/query/use-get-microagent-prompt.ts
  frontend/src/hooks/query/use-get-microagents.ts
  frontend/src/hooks/query/use-microagent-prompt.ts
  frontend/src/hooks/use-create-conversation-and-subscribe-multiple.ts
  frontend/src/i18n/declaration.ts
  frontend/src/i18n/translation.json
  frontend/src/icons/memory_icon.svg
  frontend/src/routes/conversation.tsx
  frontend/src/types/core/guards.ts
  frontend/src/types/core/variances.ts
  frontend/src/types/microagent-status.ts
  frontend/src/utils/custom-toast-handlers.tsx
  frontend/src/utils/parse-pr-url.ts
Labels: needs-review

#9668 Log vscode error in a visible way
  openhands/cli/vscode_extension.py
Labels: lint-fix

#9558 fix(frontend): The conversation page cannot be used on mobile devices and tablets.
  frontend/src/components/features/conversation/conversation-tabs.tsx
  frontend/src/components/layout/container.tsx
  frontend/src/components/layout/nav-tab.tsx
  frontend/src/components/layout/scroll-left-button.tsx
  frontend/src/components/layout/scroll-right-button.tsx
  frontend/src/hooks/use-track-element-width.ts
  frontend/src/routes/conversation.tsx
Labels: needs-qa

#9648 feat: Allow the users to edit the conversation's title.
  frontend/__tests__/components/features/conversation-panel/conversation-panel.test.tsx
  frontend/src/api/open-hands.ts
  frontend/src/components/features/conversation-panel/conversation-panel.tsx
  frontend/src/hooks/mutation/use-update-conversation.ts
  frontend/src/i18n/declaration.ts
  frontend/src/i18n/translation.json
  openhands/server/routes/manage_conversations.py
  tests/unit/test_conversation_routes.py
Labels: needs-qa

#9535 chore(ui): npm package config
  .github/workflows/npm-publish-ui.yml
  .github/workflows/ui-build.yml
  openhands-ui/PUBLISHING.md
  openhands-ui/README.md
  openhands-ui/bun.lock
  openhands-ui/index.ts
  openhands-ui/package.json
  openhands-ui/tsconfig.json
  openhands-ui/vite.config.ts
Labels: devops

#9526 Add OpenHands provider for LLM through OH Cloud
  frontend/__tests__/utils/extract-model-and-provider.test.ts
  frontend/__tests__/utils/organize-models-and-providers.test.ts
  frontend/src/components/features/settings/api-keys-manager.tsx
  frontend/src/components/features/settings/help-link.tsx
  frontend/src/components/features/settings/settings-switch.tsx
  frontend/src/components/shared/modals/settings/model-selector.tsx
  frontend/src/hooks/query/use-llm-api-key.ts
  frontend/src/i18n/declaration.ts
  frontend/src/i18n/translation.json
  frontend/src/routes/llm-settings.tsx
  frontend/src/utils/extract-model-and-provider.ts
  frontend/src/utils/map-provider.ts
  frontend/src/utils/verified-models.ts
  openhands/cli/settings.py
  openhands/cli/utils.py
  openhands/llm/llm.py
  openhands/server/mock/listen.py
  openhands/utils/llm.py
Labels: llm, needs-qa

#9746 Fix integration tests
  .github/workflows/integration-runner.yml
  evaluation/integration_tests/tests/t04_git_staging.py
Labels: integration-test

#9681 Update llm constants to match on unpinned `claude-sonnet-4`
  openhands/llm/llm.py
Labels: llm

#9314 Clarify GitHub integration docs regarding @openhands mentions in pull requests
  docs/usage/cloud/github-installation.mdx
Labels: needs-review

#9794 feat(agent): Add import placement guidance to CodeAct agent system prompts
  openhands/agenthub/codeact_agent/prompts/system_prompt.j2
  openhands/agenthub/codeact_agent/prompts/system_prompt_interactive.j2
  openhands/agenthub/codeact_agent/prompts/system_prompt_long_horizon.j2
Labels: run-eval-50

#9025 Update gitlab integration docs
  docs/usage/cloud/github-installation.mdx
  docs/usage/cloud/gitlab-installation.mdx
Labels: run-eval-1

#9828 fix(CLI): alias persistence issue
  openhands/cli/main.py
  openhands/cli/shell_config.py
  tests/unit/test_cli_alias_setup.py
Labels: needs-qa

#9489 fix(llm_config): extend retry delays to respect rate limit windows
  openhands/core/config/llm_config.py
  tests/unit/test_llm_config.py
Labels: needs-qa

#9814 Fix CLI runtime invalid path error handling
  openhands/runtime/base.py
  openhands/runtime/impl/cli/cli_runtime.py
  tests/unit/test_cli_workspace.py
Labels: needs-review

#9959 Fix user input commands being echoed twice in terminal
  frontend/src/hooks/use-terminal.ts
Labels: needs-qa

#9992 feat: the action panel / canvas can be toggled on the conversation page.
  frontend/src/components/features/chat/chat-actions.tsx
  frontend/src/components/features/conversation/conversation-main.tsx
  frontend/src/icons/block-drawer-left.svg
  frontend/src/routes/conversation.tsx
  frontend/src/state/conversation-slice.tsx
  frontend/src/store.ts
  frontend/src/tailwind.css
Labels: needs-qa

#9977 Remove task completion status message from finish action display
  frontend/__tests__/components/event-message.test.tsx
  frontend/src/components/features/chat/event-content-helpers/get-action-content.ts
  frontend/src/types/core/actions.ts
  openhands/agenthub/codeact_agent/function_calling.py
  openhands/agenthub/codeact_agent/tools/finish.py
  openhands/agenthub/loc_agent/function_calling.py
  openhands/agenthub/readonly_agent/function_calling.py
  openhands/events/action/agent.py
  openhands/events/serialization/action.py
  openhands/events/serialization/event.py
  openhands/llm/fn_call_converter.py
  tests/unit/test_action_serialization.py
  tests/unit/test_llm_fncall_converter.py
  tests/unit/test_security.py
Labels: run-eval-2
