Repository All-Hands-AI/OpenHands, pull requests merged in 2025-01, with the labels that each got.

#5991 Handle BadRequests in agent controller
  openhands/controller/agent_controller.py
Labels: lint-fix

#5986 Update github microagent for draft PRs and not creating new branches/PRs
  microagents/knowledge/github.md
Labels: lint-fix

#5783 feat(frontend): enhance GitHub repo picker with search and sorting
  frontend/__tests__/components/features/github/github-repo-selector.test.tsx
  frontend/package-lock.json
  frontend/package.json
  frontend/src/api/github.ts
  frontend/src/components/features/github/github-repo-selector.tsx
  frontend/src/components/features/github/github-repositories-suggestion-box.tsx
  frontend/src/context/settings-up-to-date-context.tsx
  frontend/src/hooks/query/use-search-repositories.ts
  frontend/src/hooks/use-click-outside-element.ts
  frontend/src/hooks/use-debounce.ts
  frontend/src/routes/_oh._index/route.tsx
  frontend/src/types/github.d.ts
  frontend/src/utils/sanitize-query.ts
  frontend/test-utils.tsx
Labels: lint-fix

#5996 Fix issue #5995: [Resolver] Resolver's summary suggests UNRESOLVED due to "no human reviewer"
  openhands/resolver/prompts/guess_success/issue-success-check.jinja
  openhands/resolver/prompts/guess_success/pr-feedback-check.jinja
  openhands/resolver/prompts/guess_success/pr-review-check.jinja
  openhands/resolver/prompts/guess_success/pr-thread-check.jinja
Labels: fix-me

#6036 fix(agent controller): state.metrics is missing on exception
  openhands/controller/agent_controller.py
  tests/unit/test_agent_controller.py
  tests/unit/test_llm.py
Labels: fix-me

#5332 Fix issue #4864: [Bug]: make start-backend results in NotImplementedError: Non-relative patterns are unsupported
  Makefile
Labels: fix-me-experimental

#6089 Fix duplicate state initialization
  openhands/controller/agent_controller.py
  openhands/server/session/agent_session.py
  tests/unit/test_agent_session.py
Labels: fix-me

#6123 Upgrade openhands-aci to 0.1.8
  poetry.lock
  pyproject.toml
Labels: run-eval-m

#6070 Improve i18n support and add missing translations
  frontend/__tests__/components/browser.test.tsx
  frontend/__tests__/components/chat/chat-input.test.tsx
  frontend/__tests__/components/features/conversation-panel/conversation-panel.test.tsx
  frontend/__tests__/components/features/github/github-repo-selector.test.tsx
  frontend/__tests__/components/features/sidebar/sidebar.test.tsx
  frontend/__tests__/components/feedback-form.test.tsx
  frontend/__tests__/components/interactive-chat-box.test.tsx
  frontend/__tests__/components/landing-translations.test.tsx
  frontend/__tests__/components/modals/settings/model-selector.test.tsx
  frontend/__tests__/components/suggestion-item.test.tsx
  frontend/__tests__/components/user-avatar.test.tsx
  frontend/__tests__/i18n/duplicate-keys.test.ts
  frontend/__tests__/i18n/translations.test.tsx
  frontend/__tests__/utils/check-hardcoded-strings.test.tsx
  frontend/__tests__/utils/i18n-test-utils.tsx
  frontend/src/components/features/browser/empty-browser-message.tsx
  frontend/src/components/features/chat/chat-input.tsx
  frontend/src/components/features/chat/chat-suggestions.tsx
  frontend/src/components/features/chat/interactive-chat-box.tsx
  frontend/src/components/features/controls/agent-control-bar.tsx
  frontend/src/components/features/conversation-panel/conversation-panel.tsx
  frontend/src/components/features/conversation-panel/new-conversation-button.tsx
  frontend/src/components/features/feedback/feedback-form.tsx
  frontend/src/components/features/github/github-repo-selector.tsx
  frontend/src/components/features/github/github-repositories-suggestion-box.tsx
  frontend/src/components/features/images/attach-image-label.tsx
  frontend/src/components/features/jupyter/jupyter-cell-output.tsx
  frontend/src/components/features/sidebar/user-avatar.tsx
  frontend/src/components/features/suggestions/import-project-suggestion-box.tsx
  frontend/src/components/features/suggestions/suggestion-bubble.tsx
  frontend/src/components/features/suggestions/suggestion-item.tsx
  frontend/src/components/features/terminal/terminal-status-label.tsx
  frontend/src/components/features/waitlist/tos-checkbox.tsx
  frontend/src/components/layout/beta-badge.tsx
  frontend/src/components/layout/served-app-label.tsx
  frontend/src/components/shared/action-tooltip.tsx
  frontend/src/components/shared/buttons/docs-button.tsx
  frontend/src/components/shared/buttons/exit-project-button.tsx
  frontend/src/components/shared/buttons/open-vscode-button.tsx
  frontend/src/components/shared/buttons/settings-button.tsx
  frontend/src/components/shared/buttons/stop-button.tsx
  frontend/src/components/shared/buttons/submit-button.tsx
  frontend/src/components/shared/download-progress.tsx
  frontend/src/components/shared/hero-heading.tsx
  frontend/src/components/shared/inputs/api-key-input.tsx
  frontend/src/components/shared/modals/account-settings/account-settings-form.tsx
  frontend/src/components/shared/modals/settings/model-selector.tsx
  frontend/src/components/shared/modals/settings/runtime-size-selector.tsx
  frontend/src/components/shared/modals/settings/settings-form.tsx
  frontend/src/components/shared/modals/settings/settings-modal.tsx
  frontend/src/components/shared/task-form.tsx
  frontend/src/i18n/index.ts
  frontend/src/i18n/translation.json
  frontend/src/routes/_oh._index/route.tsx
  frontend/src/routes/_oh.app/route.tsx
  frontend/src/utils/suggestions/non-repo-suggestions.ts
  frontend/src/utils/suggestions/repo-suggestions.ts
  package-lock.json
  package.json
Labels: fix-me

#6165 Delegation fixes
  .github/workflows/integration-runner.yml
  evaluation/integration_tests/run_infer.py
  evaluation/integration_tests/scripts/run_infer.sh
  openhands/agenthub/micro/agent.py
  openhands/controller/agent_controller.py
  openhands/events/stream.py
  openhands/runtime/base.py
  tests/unit/test_agent_controller.py
  tests/unit/test_agent_delegation.py
Labels: integration-test

#6239 Fix microagent loading with trailing slashes and nested directories
  openhands/microagent/microagent.py
  openhands/resolver/patching/patch.py
  openhands/runtime/base.py
  tests/runtime/conftest.py
  tests/runtime/test_bash.py
  tests/runtime/test_ipython.py
  tests/runtime/test_microagent.py
  tests/unit/resolver/test_patch_apply.py
  tests/unit/test_microagent_utils.py
Labels: lint-fix

#6274 Fix issue #6273: [Feature]: Disable LitLLM Print Message
  openhands/core/logger.py
  pyproject.toml
  tests/unit/test_logger_litellm.py
Labels: fix-me, lint-fix

#6313 feat(eval): misc SWE-Bench improvement - use different resources for different instances
  evaluation/benchmarks/swe_bench/eval_infer.py
  evaluation/benchmarks/swe_bench/resource/mapping.py
  evaluation/benchmarks/swe_bench/resource/princeton-nlp__SWE-bench_Verified-test.json
  evaluation/benchmarks/swe_bench/run_infer.py
  evaluation/benchmarks/swe_bench/scripts/eval/combine_final_completions.py
  evaluation/benchmarks/swe_bench/scripts/eval/convert_oh_output_to_swe_json.py
  evaluation/benchmarks/swe_bench/scripts/eval/update_output_with_eval.py
  evaluation/benchmarks/swe_bench/scripts/run_infer.sh
Labels: fix-me

#5506 Adjust prompt to use view command
  openhands/agenthub/codeact_agent/prompts/system_prompt.j2
Labels: lint-fix

#6067 Edit tool prompt tweaking: only plain-text format is supported
  openhands/agenthub/codeact_agent/function_calling.py
Labels: run-eval-m

#6471 Fix first user message
  openhands/agenthub/codeact_agent/codeact_agent.py
  openhands/core/config/sandbox_config.py
  openhands/llm/fn_call_converter.py
  openhands/runtime/impl/remote/remote_runtime.py
  openhands/utils/prompt.py
  poetry.lock
  tests/unit/test_prompt_manager.py
Labels: integration-test
