Repository All-Hands-AI/OpenHands, pull requests merged in 2025-02, with the labels that each got.

#6596 Simplify fn calling usage
  openhands/agenthub/codeact_agent/codeact_agent.py
  openhands/llm/llm.py
  tests/unit/test_codeact_agent.py
Labels: integration-test

#6533 Fix issue #6531: [Bug]: GITHUB_TOKEN would missing when the runtime resume
  openhands/runtime/base.py
  openhands/runtime/impl/docker/docker_runtime.py
  tests/runtime/test_env_vars.py
Labels: lint-fix

#6620 Fix memory leak in JSON encoder
  openhands/core/utils/json.py
  tests/unit/test_json_encoder.py
Labels: fix-me

#6675 Clean up global in llm.py (we figured it's not needed)
  openhands/agenthub/codeact_agent/codeact_agent.py
  openhands/llm/llm.py
Labels: integration-test

#5398 docs: improve docstrings for CLI and config utils
  docs/modules/usage/architecture/runtime.md
  openhands/README.md
  openhands/core/cli.py
  openhands/core/config/utils.py
  openhands/core/main.py
  openhands/core/message.py
  openhands/llm/llm.py
  openhands/runtime/impl/docker/docker_runtime.py
  openhands/runtime/plugins/agent_skills/file_ops/file_ops.py
  openhands/runtime/utils/runtime_build.py
  openhands/server/routes/public.py
  tests/unit/test_micro_agents.py
Labels: Stale

#6260 Clean up NullObservations from the stream
  openhands/agenthub/dummy_agent/agent.py
  openhands/core/cli.py
  openhands/events/utils.py
  openhands/runtime/base.py
Labels: integration-test

#6187 Refactor I/O utils; allow 'task' command line parameter in cli.py
  openhands/agenthub/micro/agent.py
  openhands/core/cli.py
  openhands/core/main.py
  openhands/core/utils/__init__.py
  openhands/events/stream.py
  openhands/io/__init__.py
  openhands/io/io.py
  openhands/io/json.py
  openhands/llm/llm.py
  tests/unit/test_cli.py
  tests/unit/test_json.py
  tests/unit/test_json_encoder.py
  tests/unit/test_response_parsing.py
Labels: lint-fix, openhands

#6687 fix: Add missing type annotations in utils/ directory
  openhands/utils/http_session.py
  openhands/utils/prompt.py
  openhands/utils/shutdown_listener.py
  openhands/utils/tenacity_stop.py
Labels: run-eval-s

#6898 Display session ID in CLI mode
  openhands/core/cli.py
  tests/unit/test_cli_sid.py
Labels: lint-fix

#5932 add extended generic section
  openhands/core/config/__init__.py
  openhands/core/config/app_config.py
  openhands/core/config/extended_config.py
  openhands/core/config/utils.py
  tests/unit/test_config_extended.py
Labels: lint-fix

#6949 Add selected_repo to command line
  .github/workflows/integration-runner.yml
  evaluation/benchmarks/EDA/run_infer.py
  evaluation/benchmarks/agent_bench/run_infer.py
  evaluation/benchmarks/aider_bench/run_infer.py
  evaluation/benchmarks/biocoder/run_infer.py
  evaluation/benchmarks/bird/run_infer.py
  evaluation/benchmarks/commit0_bench/run_infer.py
  evaluation/benchmarks/discoverybench/run_infer.py
  evaluation/benchmarks/gaia/run_infer.py
  evaluation/benchmarks/gorilla/run_infer.py
  evaluation/benchmarks/gpqa/run_infer.py
  evaluation/benchmarks/humanevalfix/run_infer.py
  evaluation/benchmarks/logic_reasoning/run_infer.py
  evaluation/benchmarks/miniwob/run_infer.py
  evaluation/benchmarks/mint/run_infer.py
  evaluation/benchmarks/ml_bench/run_infer.py
  evaluation/benchmarks/scienceagentbench/run_infer.py
  evaluation/benchmarks/swe_bench/run_infer.py
  evaluation/benchmarks/the_agent_company/run_infer.py
  evaluation/benchmarks/toolqa/run_infer.py
  evaluation/benchmarks/visualwebarena/run_infer.py
  evaluation/benchmarks/webarena/run_infer.py
  evaluation/integration_tests/run_infer.py
  openhands/core/cli.py
  openhands/core/config/sandbox_config.py
  openhands/core/config/utils.py
  openhands/core/main.py
  openhands/core/setup.py
  tests/unit/test_arg_parser.py
Labels: integration-test, run-eval-xs

#6963 Fix microagent matching to the user message, not previous enhancements
  openhands/utils/prompt.py
  tests/unit/test_prompt_manager.py
Labels: openhands

#6967 Refactor agent_config loading from toml
  openhands/core/config/agent_config.py
  openhands/core/config/utils.py
  tests/unit/test_config.py
Labels: run-eval-xs

#7008 Refactor to a helper class for the agent's history (ConversationMemory)
  openhands/agenthub/codeact_agent/codeact_agent.py
  openhands/core/message_utils.py
  openhands/memory/conversation_memory.py
  openhands/security/invariant/analyzer.py
  openhands/security/invariant/nodes.py
  tests/unit/test_conversation_memory.py
  tests/unit/test_message_utils.py
Labels: integration-test, run-eval-s

#7024 Fix: Update context window exceeded detection
  openhands/controller/agent_controller.py
Labels: lint-fix
