Repository All-Hands-AI/OpenHands, pull requests merged in 2025-09, with the labels that each got.

#10852 refactor(frontend): standardize font colors and sizes in empty state
  frontend/src/components/features/browser/empty-browser-message.tsx
Labels: deploy

#9738 Implement model routing support
  config.template.toml
  evaluation/benchmarks/gaia/run_infer.py
  evaluation/benchmarks/swe_bench/run_infer.py
  openhands/agenthub/codeact_agent/codeact_agent.py
  openhands/core/config/__init__.py
  openhands/core/config/agent_config.py
  openhands/core/config/llm_config.py
  openhands/core/config/model_routing_config.py
  openhands/core/config/openhands_config.py
  openhands/core/config/utils.py
  openhands/llm/llm_registry.py
  openhands/llm/router/README.md
  openhands/llm/router/__init__.py
  openhands/llm/router/base.py
  openhands/llm/router/rule_based/impl.py
Labels: enhancement, agent

#10905 Refactor(V1): OpenHands CLI + Agent SDK
  .github/workflows/cli-build-test.yml
  .github/workflows/lint.yml
  .github/workflows/py-tests.yml
  .gitignore
  dev_config/python/.pre-commit-config.yaml
  openhands-cli/.gitignore
  openhands-cli/Makefile
  openhands-cli/README.md
  openhands-cli/build.py
  openhands-cli/build.sh
  openhands-cli/openhands-cli.spec
  openhands-cli/openhands_cli/__init__.py
  openhands-cli/openhands_cli/agent_chat.py
  openhands-cli/openhands_cli/listeners/__init__.py
  openhands-cli/openhands_cli/listeners/pause_listener.py
  openhands-cli/openhands_cli/pt_style.py
  openhands-cli/openhands_cli/runner.py
  openhands-cli/openhands_cli/setup.py
  openhands-cli/openhands_cli/simple_main.py
  openhands-cli/openhands_cli/tui.py
  openhands-cli/openhands_cli/user_actions/__init__.py
  openhands-cli/openhands_cli/user_actions/agent_action.py
  openhands-cli/openhands_cli/user_actions/exit_session.py
  openhands-cli/openhands_cli/user_actions/types.py
  openhands-cli/openhands_cli/user_actions/utils.py
  openhands-cli/pyproject.toml
  openhands-cli/tests/__init__.py
  openhands-cli/tests/test_confirmation_mode.py
  openhands-cli/tests/test_conversation_runner.py
  openhands-cli/tests/test_exit_session_confirmation.py
  openhands-cli/tests/test_main.py
  openhands-cli/tests/test_pause_listener.py
  openhands-cli/tests/test_tui.py
  openhands-cli/tests/utils.py
  openhands-cli/uv.lock
Labels: v1

#10890 feat: Upgrade banner for unsubscribed SaaS users
  enterprise/migrations/versions/075_add_cancellation_fields_to_subscription_access.py
  enterprise/server/routes/billing.py
  enterprise/storage/subscription_access.py
  enterprise/tests/unit/test_billing.py
  frontend/__tests__/components/features/payment/payment-form.test.tsx
  frontend/__tests__/routes/llm-settings.test.tsx
  frontend/__tests__/routes/settings-with-payment.test.tsx
  frontend/__tests__/routes/settings.test.tsx
  frontend/src/api/billing-service/billing-service.api.ts
  frontend/src/api/billing-service/billing.types.ts
  frontend/src/components/features/context-menu/account-settings-context-menu.tsx
  frontend/src/components/features/payment/cancel-subscription-modal.tsx
  frontend/src/components/features/payment/payment-form.tsx
  frontend/src/components/features/settings/banner-message.tsx
  frontend/src/components/features/settings/brand-button.tsx
  frontend/src/components/features/settings/index.ts
  frontend/src/components/features/settings/pro-pill.tsx
  frontend/src/components/features/settings/settings-switch.tsx
  frontend/src/components/features/settings/upgrade-banner-with-backdrop.tsx
  frontend/src/components/features/settings/upgrade-banner.tsx
  frontend/src/components/features/settings/upgrade-button.tsx
  frontend/src/hooks/mutation/stripe/use-create-subscription-checkout-session.ts
  frontend/src/hooks/mutation/use-cancel-subscription.ts
  frontend/src/i18n/declaration.ts
  frontend/src/i18n/translation.json
  frontend/src/mocks/billing-handlers.ts
  frontend/src/routes/llm-settings.tsx
  frontend/src/routes/settings.tsx
Labels: deploy

#11022 Hotfix: rm model choice override
  enterprise/experiments/experiment_manager.py
Labels: deploy

#11113 fix(backend): Add validation for LLM settings to prevent non-pro user bypass
  openhands/server/routes/settings.py
  openhands/server/settings_validation.py
  tests/unit/server/routes/test_settings_security.py
Labels: deploy

#11169 Remove legacy README_CN.md and README_JA.md translation files
  README_CN.md
  README_JA.md
Labels: documentation

#11155 fix: add provider tokens to resume conversation endpoint
  openhands/integrations/provider.py
  openhands/server/routes/manage_conversations.py
  openhands/server/services/conversation_service.py
  tests/unit/server/routes/test_start_endpoint.py
  tests/unit/server/services/test_conversation_service.py
Labels: deploy
