Repository All-Hands-AI/OpenHands, pull requests merged in 2025-03, with the labels that each got.

#7036 [Refactor] split runtime initialization (create, connect, init) in cli scripts
  evaluation/benchmarks/EDA/run_infer.py
  evaluation/benchmarks/agent_bench/run_infer.py
  evaluation/benchmarks/aider_bench/run_infer.py
  evaluation/benchmarks/biocoder/run_infer.py
  evaluation/benchmarks/bird/run_infer.py
  evaluation/benchmarks/browsing_delegation/run_infer.py
  evaluation/benchmarks/commit0_bench/run_infer.py
  evaluation/benchmarks/discoverybench/run_infer.py
  evaluation/benchmarks/gaia/run_infer.py
  evaluation/benchmarks/gorilla/run_infer.py
  evaluation/benchmarks/gpqa/run_infer.py
  evaluation/benchmarks/humanevalfix/run_infer.py
  evaluation/benchmarks/logic_reasoning/run_infer.py
  evaluation/benchmarks/miniwob/run_infer.py
  evaluation/benchmarks/mint/run_infer.py
  evaluation/benchmarks/ml_bench/run_infer.py
  evaluation/benchmarks/scienceagentbench/run_infer.py
  evaluation/benchmarks/swe_bench/run_infer.py
  evaluation/benchmarks/the_agent_company/run_infer.py
  evaluation/benchmarks/toolqa/run_infer.py
  evaluation/benchmarks/visualwebarena/run_infer.py
  evaluation/benchmarks/webarena/run_infer.py
  evaluation/integration_tests/run_infer.py
  openhands/core/cli.py
  openhands/core/main.py
  openhands/core/setup.py
Labels: integration-test, run-eval-s

#7082 Expose accumulate and llm_metric from eventstream to frontend (backend only)
  openhands/controller/agent_controller.py
  openhands/events/serialization/event.py
  tests/unit/test_agent_controller.py
  tests/unit/test_event_serialization.py
Labels: integration-test

#7151 remove llamaindex
  .github/dependabot.yml
  .github/workflows/dummy-agent-test.yml
  .github/workflows/integration-runner.yml
  .github/workflows/py-unit-tests.yml
  Makefile
  config.template.toml
  containers/app/Dockerfile
  docs/modules/usage/configuration-options.md
  docs/modules/usage/llms/azure-llms.md
  openhands/core/config/agent_config.py
  openhands/core/config/llm_config.py
  openhands/core/config/utils.py
  openhands/memory/README.md
  openhands/memory/__init__.py
  openhands/memory/long_term_memory.py
  openhands/utils/embeddings.py
  poetry.lock
  pyproject.toml
  tests/unit/test_config.py
  tests/unit/test_config_extended.py
  tests/unit/test_llm_config.py
  tests/unit/test_llm_draft_config.py
  tests/unit/test_long_term_memory.py
  tests/unit/test_micro_agents.py
Labels: lint-fix

#6964 remove old microagents
  .github/workflows/integration-runner.yml
  microagents/knowledge/swift-linux.md
  openhands/agenthub/__init__.py
  openhands/agenthub/micro/README.md
  openhands/agenthub/micro/_instructions/actions/browse.md
  openhands/agenthub/micro/_instructions/actions/delegate.md
  openhands/agenthub/micro/_instructions/actions/finish.md
  openhands/agenthub/micro/_instructions/actions/kill.md
  openhands/agenthub/micro/_instructions/actions/message.md
  openhands/agenthub/micro/_instructions/actions/read.md
  openhands/agenthub/micro/_instructions/actions/reject.md
  openhands/agenthub/micro/_instructions/actions/run.md
  openhands/agenthub/micro/_instructions/actions/write.md
  openhands/agenthub/micro/_instructions/format/action.md
  openhands/agenthub/micro/_instructions/history_truncated.md
  openhands/agenthub/micro/agent.py
  openhands/agenthub/micro/coder/agent.yaml
  openhands/agenthub/micro/coder/prompt.md
  openhands/agenthub/micro/commit_writer/README.md
  openhands/agenthub/micro/commit_writer/agent.yaml
  openhands/agenthub/micro/commit_writer/prompt.md
  openhands/agenthub/micro/instructions.py
  openhands/agenthub/micro/manager/agent.yaml
  openhands/agenthub/micro/manager/prompt.md
  openhands/agenthub/micro/math_agent/agent.yaml
  openhands/agenthub/micro/math_agent/prompt.md
  openhands/agenthub/micro/postgres_agent/agent.yaml
  openhands/agenthub/micro/postgres_agent/prompt.md
  openhands/agenthub/micro/registry.py
  openhands/agenthub/micro/repo_explorer/agent.yaml
  openhands/agenthub/micro/repo_explorer/prompt.md
  openhands/agenthub/micro/study_repo_for_task/agent.yaml
  openhands/agenthub/micro/study_repo_for_task/prompt.md
  openhands/agenthub/micro/typo_fixer_agent/agent.yaml
  openhands/agenthub/micro/typo_fixer_agent/prompt.md
  openhands/agenthub/micro/verifier/agent.yaml
  openhands/agenthub/micro/verifier/prompt.md
  openhands/core/setup.py
  openhands/events/serialization/event.py
  tests/unit/test_iteration_limit.py
  tests/unit/test_micro_agents.py
  tests/unit/test_response_parsing.py
Labels: lint-fix

#6909 Add RecallObservations for retrieval of prompt extensions
  openhands/agenthub/codeact_agent/codeact_agent.py
  openhands/agenthub/codeact_agent/prompts/additional_info.j2
  openhands/agenthub/codeact_agent/prompts/microagent_info.j2
  openhands/controller/agent_controller.py
  openhands/controller/stuck.py
  openhands/core/cli.py
  openhands/core/loop.py
  openhands/core/main.py
  openhands/core/schema/action.py
  openhands/core/schema/observation.py
  openhands/core/setup.py
  openhands/events/__init__.py
  openhands/events/action/__init__.py
  openhands/events/action/agent.py
  openhands/events/event.py
  openhands/events/observation/__init__.py
  openhands/events/observation/agent.py
  openhands/events/serialization/action.py
  openhands/events/serialization/event.py
  openhands/events/serialization/observation.py
  openhands/events/stream.py
  openhands/llm/llm.py
  openhands/memory/conversation_memory.py
  openhands/memory/memory.py
  openhands/server/session/agent_session.py
  openhands/storage/conversation/file_conversation_store.py
  openhands/utils/prompt.py
  tests/unit/test_action_serialization.py
  tests/unit/test_agent_controller.py
  tests/unit/test_agent_delegation.py
  tests/unit/test_agent_session.py
  tests/unit/test_cli_sid.py
  tests/unit/test_codeact_agent.py
  tests/unit/test_conversation_memory.py
  tests/unit/test_is_stuck.py
  tests/unit/test_memory.py
  tests/unit/test_observation_serialization.py
  tests/unit/test_prompt_manager.py
Labels: backend, architecture, microagents

#7278 Fix visual browsing
  openhands/agenthub/visualbrowsing_agent/visualbrowsing_agent.py
  openhands/memory/conversation_memory.py
Labels: integration-test

#7247 [Fix]: Plumb provider tokens to runtime
  openhands/core/setup.py
  openhands/integrations/gitlab/gitlab_service.py
  openhands/integrations/provider.py
  openhands/integrations/service_types.py
  openhands/runtime/base.py
  openhands/runtime/impl/action_execution/action_execution_client.py
  openhands/runtime/impl/remote/remote_runtime.py
  openhands/server/auth.py
  openhands/server/routes/manage_conversations.py
  openhands/server/session/agent_session.py
  openhands/server/session/conversation_init_data.py
  openhands/server/session/session.py
  poetry.lock
  pyproject.toml
  tests/unit/test_provider_immutability.py
  tests/unit/test_runtime_git_tokens.py
Labels: lint-fix

#5985 Add support for .openhands/setup.sh script
  docs/modules/usage/customization/repository.md
  docs/sidebars.ts
  openhands/runtime/base.py
  openhands/server/session/agent_session.py
Labels: fix-me-experimental

#7518 Feat vscode startup
  openhands/runtime/plugins/vscode/__init__.py
  openhands/runtime/plugins/vscode/settings.json
  openhands/runtime/utils/runtime_templates/Dockerfile.j2
  openhands/server/file_config.py
Labels: lint-fix
