Repository All-Hands-AI/OpenHands, pull requests merged in 2025-04, with the labels that each got.

#7655 Fix issue #7205: [Feature]: Allow repo microagent Markdown Files Without Required Header
  microagents/README.md
  openhands/integrations/gitlab/gitlab_service.py
  openhands/memory/memory.py
  openhands/microagent/microagent.py
  openhands/microagent/types.py
  openhands/runtime/impl/docker/docker_runtime.py
  openhands/server/routes/git.py
  openhands/server/session/agent_session.py
  poetry.lock
  pyproject.toml
  tests/unit/test_memory.py
  tests/unit/test_microagent_no_header.py
Labels: lint-fix

#7660 Fix issue #7658: [Bug]: BadRequestError from ContentPolicyViolationError
  frontend/src/i18n/translation.json
  openhands/controller/agent_controller.py
  tests/unit/test_agent_controller.py
Labels: lint-fix

#7727 Add more extensive typing to openhands/llm/ directory
  openhands/llm/async_llm.py
  openhands/llm/bedrock.py
  openhands/llm/debug_mixin.py
  openhands/llm/llm.py
  openhands/llm/metrics.py
  openhands/llm/retry_mixin.py
  openhands/llm/streaming_llm.py
Labels: integration-test

#7747 Fix integration test
  evaluation/integration_tests/tests/t04_git_staging.py
Labels: integration-test

#6284 Fix issue #6037: [Bug]: [Resolver] crashes on `main`
  openhands/runtime/utils/log_streamer.py
  tests/unit/test_log_streamer.py
Labels: lint-fix

#7898 [Feat] Support o3 and o4 mini
  docs/modules/usage/llms/llms.md
  frontend/src/utils/verified-models.ts
  openhands/llm/llm.py
Labels: lint-fix

#7612 feat: add argument --base-container-image to resolver
  openhands/core/config/sandbox_config.py
  openhands/resolver/resolve_all_issues.py
  openhands/resolver/resolve_issue.py
  openhands/runtime/builder/docker.py
  openhands/runtime/impl/remote/remote_runtime.py
  poetry.lock
  tests/unit/resolver/github/test_resolve_issues.py
  tests/unit/resolver/gitlab/test_gitlab_resolve_issues.py
Labels: lint-fix

#8011 Release 0.34.0
  Development.md
  README.md
  containers/dev/compose.yml
  docker-compose.yml
  docs/i18n/fr/docusaurus-plugin-content-docs/current/usage/how-to/cli-mode.md
  docs/i18n/fr/docusaurus-plugin-content-docs/current/usage/how-to/headless-mode.md
  docs/i18n/fr/docusaurus-plugin-content-docs/current/usage/installation.mdx
  docs/i18n/fr/docusaurus-plugin-content-docs/current/usage/runtimes.md
  docs/i18n/ja/docusaurus-plugin-content-docs/current/usage/how-to/cli-mode.md
  docs/i18n/ja/docusaurus-plugin-content-docs/current/usage/how-to/headless-mode.md
  docs/i18n/ja/docusaurus-plugin-content-docs/current/usage/runtimes/docker.md
  docs/i18n/pt-BR/docusaurus-plugin-content-docs/current/usage/how-to/cli-mode.md
  docs/i18n/pt-BR/docusaurus-plugin-content-docs/current/usage/how-to/headless-mode.md
  docs/i18n/pt-BR/docusaurus-plugin-content-docs/current/usage/installation.mdx
  docs/i18n/pt-BR/docusaurus-plugin-content-docs/current/usage/runtimes.md
  docs/i18n/zh-Hans/docusaurus-plugin-content-docs/current/usage/how-to/cli-mode.md
  docs/i18n/zh-Hans/docusaurus-plugin-content-docs/current/usage/how-to/headless-mode.md
  docs/i18n/zh-Hans/docusaurus-plugin-content-docs/current/usage/installation.mdx
  docs/i18n/zh-Hans/docusaurus-plugin-content-docs/current/usage/runtimes.md
  docs/modules/usage/how-to/cli-mode.md
  docs/modules/usage/how-to/headless-mode.md
  docs/modules/usage/installation.mdx
  frontend/package-lock.json
  frontend/package.json
  pyproject.toml
Labels: run-eval-xs

#8168 Fix ValueError when latest_event_id is undefined
  openhands/server/listen_socket.py
Labels: lint-fix
